version: '3.9'
name: game-microservices-db

services:
  auth-db:
    image: mongo:4.4.7
    platform: linux/amd64
    container_name: auth-db
    ports:
      - '27011:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  inventory-db:
    image: mongo:4.4.7
    platform: linux/amd64
    container_name: inventory-db
    ports:
      - '27012:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  item-db:
    image: mongo:4.4.7
    platform: linux/amd64
    container_name: item-db
    ports:
      - '27013:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  payment-db:
    image: mongo:4.4.7
    platform: linux/amd64
    container_name: payment-db
    ports:
      - '27014:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  player-db:
    image: mongo:4.4.7
    platform: linux/amd64
    container_name: player-db
    ports:
      - '27015:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin